# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rgbd_proto.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10rgbd_proto.proto\x12\x08mpb_test\"q\n\x0eTargetLocation\x12\n\n\x02x1\x18\x01 \x01(\x01\x12\n\n\x02y1\x18\x02 \x01(\x01\x12\n\n\x02z1\x18\x03 \x01(\x01\x12\n\n\x02x2\x18\x04 \x01(\x01\x12\n\n\x02y2\x18\x05 \x01(\x01\x12\n\n\x02z2\x18\x06 \x01(\x01\x12\x0b\n\x03seq\x18\x07 \x01(\r\x12\n\n\x02ts\x18\x08 \x01(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rgbd_proto_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _TARGETLOCATION._serialized_start = 30
    _TARGETLOCATION._serialized_end = 143
# @@protoc_insertion_point(module_scope)
