# basic information
Corporation: hqx
Project: AI Software Platform
Develop:
  group: algorithm
  authors: Ycc, Jim

# running configurations
log:
  log_dir: './logs/'    # ./logs/{data_time}.txt

models:
  detect:
    valid: True
    cuda: 0
    port: 0
    platform: pc          # pc(onnx) / rknn(rknn)
    weight: '/home/ycc/Jim/yolov5/models/yolov5s-det-0724.onnx'
    imgsz: 640
    obj_threshold: 0.5
    nms_threshold: 0.5

  segment:
    valid: False
    cuda: 0
    port: 1
    platform: pc
    weight: '/home/ycc/Jim/yolov5/models/yolov5n-seg-0724.onnx'
    imgsz: 640
    obj_threshold: 0.5
    nms_threshold: 0.5

cameras:
  realsense:

  fish:
    hub: 0
    width: 1600
    height: 1200
    fps: 25

connections:
  valid: True

  detect:
    zmq:
      addr: "tcp://*:8003"

  segment:
    zmq:
      addr: "tcp://*:8004"
