# basic information
Corporation: hqx
Project: AI Software Platform
Develop:
  group: algorithm
  authors: Ycc, Jim

# running configurations
log:
  log_dir: './logs/'    # ./logs/{data_time}.txt

visualization: True

models:
  detect:
    valid: False
    cuda: 0
    port: 0
    platform: pc          # pc(onnx) / rknn(rknn)
    weight: 'algorithm/weights/yolov5s-det-0724-noquan.rknn'
    imgsz: 640
    obj_threshold: 0.5
    nms_threshold: 0.5

  segment:
    valid: True
    cuda: 0
    port: 1
    platform: pc
    weight: 'algorithm/weights/yolov5n-seg-0724-noquan.rknn'
    imgsz: 640
    obj_threshold: 0.7
    nms_threshold: 0.5

cameras:
  realsense:

  fish:
    hub: 4
    width: 1600
    height: 1200
    fps: 25
    distorted: False

  doubleFish: True
  fishL:
    hub: 0
    width: 1600
    height: 1200
    fps: 25
    distorted: False

  fishR:
    hub: 1
    width: 1600
    height: 1200
    fps: 25
    distorted: False

connections:
  valid: True

  detect:
    zmq:
      addr: "tcp://*:8003"

  segment:
    zmq:
      addr: "tcp://*:8013"
