# basic information
Corporation: hqx
Project: AI Software Platform
Develop:
  group: algorithm
  authors: Ycc, Jim

# running configurations
log:
  log_dir: './logs/'    # ./logs/{data_time}.txt

models:
  detect:
    valid: True
    cuda: 0
    port: 0
    platform: pc          # pc(onnx) / rknn(rknn)
    weight: '/home/ycc/PycharmProjects/yolov5/runs/train/exp8/weights/best.onnx'
    imgsz: 640
    obj_threshold: 0.3
    nms_threshold: 0.5

  segment:
    valid: True
    cuda: 0
    port: 1
    platform: pc
    weight: '/home/ycc/PycharmProjects/yolov5/runs/train-seg/exp5/weights/best.onnx'
    imgsz: 640
    obj_threshold: 0.3
    nms_threshold: 0.5

cameras:
  realsense:

  fish:
    hub: 4
    width: 1600
    height: 1200
    fps: 25

connections:
  detect:
    zmq:
      addr: "tcp://*:8003"

  segment:
    zmq:
      addr: "tcp://*:8004"
