# basic information
Corporation: hqx
Project: AI Software Platform
Develop:
  group: algorithm
  authors: Ycc, Jim

# running configurations
log:
  log_dir: './logs/'    # ./logs/{data_time}.txt

visualization: True

models:
  detect:
    valid: True
    cuda: 0
    port: 0
    platform: pc          # pc(onnx) / rknn(rknn)
    #    weight: 'algorithm/weights/yolov5s-det-0724-noquan.rknn'
    weight: '/home/ycc/Jim/yolov5/models/yolov5s-det-0728.onnx'
    imgsz: 640
    obj_threshold: 0.5
    nms_threshold: 0.5

  segment:
    valid: True
    cuda: 0
    port: 1
    platform: pc
    #    weight: 'algorithm/weights/yolov5n-seg-0724-noquan.rknn'
    weight: '/home/ycc/Jim/yolov5/models/yolov5n-seg-0724.onnx'
    imgsz: 640
    obj_threshold: 0.7
    nms_threshold: 0.5

cameras:
  realsense:

  fish:
    hub: 4
    width: 1600
    height: 1200
    fps: 25
    distorted: True
    k: [[812.0759926090558, 0.0, 810.3963949199671], [0.0, 813.5716912856911, 606.0612337205697], [0.0, 0.0, 1.0]]
    d: [[0.5033714773685056], [0.12237339795797722], [-0.41302582292485795], [0.4501049351340188]]

  doubleFish: True
  fishL:
    hub: 0
    width: 1600
    height: 1200
    fps: 25
    distorted: False

  fishR:
    hub: 1
    width: 1600
    height: 1200
    fps: 25
    distorted: False

connections:
  valid: True

  detect:
    zmq:
      addr: "tcp://*:8003"

  segment:
    zmq:
      addr: "tcp://*:8013"
